### ISSUE TITLE
Error: Cannot resolve type entity i1.FontAwesomeModule to symbol

### ISSUE THREAD

**Issue by eng-dibo** [FortAwesome/angular-fontawesome#366] opened 2022-05-30 19:01 UTC
### Describe the problem

when I run `ng build` I get this error
```
Error: Module build failed (from ../../node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i1.FontAwesomeModule to symbol
    at node_modules\@ngtools\webpack\src\ivy\loader.js:81:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### What did you expect?

to build without errors

### Reproducible test case

[repo](https://github.com/eng-dibo/dibo/tree/issue/build)
run `cd ngx-cms && npm run tmp`

**Comment by devoto13** [comment] 2022-05-30 22:24
I'm not sure how I can help here as there is nothing wrong with the `angular-fontawesome` library AFAICT.

The problem seems to lay somewhere in your monorepo setup, Angular builds tooling, or how they interact with each other. For some reason the library is not hoisted from `packages/ngx-content-view-mat/node_modules/@fortawesome/angular-fontawesome` to the `node_modules/@fortawesome/angular-fontawesome` and reading [this](https://github.com/ng-packagr/ng-packagr/issues/2225#issuecomment-1016172549) makes me think that Angular is looking for the library in the wrong place and that's what causes the reported error. Indeed manually *hoisting* the library using `mv packages/ngx-content-view-mat/node_modules/@fortawesome/angular-fontawesome node_modules/@fortawesome` fixes the reported error.

**Comment by eng-dibo** [comment] 2022-05-30 22:36
> the library is not hoisted from `packages/ngx-content-view-mat/node_modules/@fortawesome/angular-fontawesome`

yes, this is another issue I'm looking to fix, but before I opened this issue I manually hoisted all dependencies from all packages and projects into the root node_modules but the same error occures.

**Comment by devoto13** [comment] 2022-05-31 13:50
@eng-dibo I don't know why is it not working for you, but for me running the below commands fixes the `Cannot resolve type entity i1.FontAwesomeModule to symbol` error (build still fails with a lot of other errors though):

```bash
$ git clone git@github.com:eng-dibo/dibo.git
$ cd dibo
$ mv packages/ngx-content-view-mat/node_modules/@fortawesome/angular-fontawesome node_modules/@fortawesome
$ cd projects/ngx-cms
$ ./node_modules/.bin/ng build
```

As I said before, the problem seems to be related to the monorepo setup and/or Angular build tooling, so I'm not sure how else can I help here.

**Comment by alexandis** [comment] 2022-07-27 11:08
At least topic starter knows what type is complained about. But how do I know which type is meant, if the error message looks like this:

> ./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
> Error: Cannot resolve type entity i6.ɵx to symbol
>     at D:\CT\AbxEps.MasterData\angular\node_modules\@ngtools\webpack\src\ivy\loader.js:81:18
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at runNextTicks (node:internal/process/task_queues:65:3)
>     at processImmediate (node:internal/timers:437:9)

?
I run "ng serve" and get this error above.
Setting preserveSymlinks to true in angular.json did not help.

**Comment by devoto13** [comment] 2022-07-27 11:22
@alexandis One option is to run `ng serve` with the debugger attached, put a breakpoint in the `node_modules@ngtools\webpack\src\ivy\loader.js` on line 81 and check the file name from the `this.resourcePath` variable.

**Comment by devoto13** [comment] 2022-07-27 11:29
I'm going to close this as there is nothing wrong with the `angular-fontawesome` library, but the problem is caused by the bug in Angular build tooling or the the author's monorepo setup being unsupported by the Angular build tooling. Either way, there is nothing we can do in the `angular-fontawesome` library to resolve this.

**Closed by devoto13** 2022-07-27 11:29 UTC

**Comment by alexandis** [comment] 2022-07-27 11:54
> One option is to run `ng serve` with the debugger attached

Could you please just let me know how to do this? When I just set breakpoint in the given place and rerun the site - it is not triggered. Obviously because the site is not run, since it was a compile error...

**Comment by devoto13** [comment] 2022-07-27 12:01
You'll need to attach the debugger to the Node process building the application, not to the application running in the browser. If you use VS Code, then something like the below in the `.vscode/launch.json` should work:

```
        {
            "type": "node",
            "request": "launch",
            "name": "ng serve",
            "program": "${workspaceFolder}/node_modules/@angular/cli/bin/ng.js",
            "args": ["serve"]
        }
```

**Comment by alexandis** [comment] 2022-07-27 12:52
@devoto13 Good news is I was able to trigger breakpoint in exception. Thank you very much for this launch configuration thing. Bad news is that I was unable to find that erroneous entity type: in the exception block the context is lost and the place where it happens is emitting `polyfills.ts` (this is what `resourcePath` tells me)... Does not help much, alas...
Well, don't want to bother you further with that :)

**Comment by dds05** [comment] 2023-02-13 14:33
@alexandis Any update?

**Comment by alexandis** [comment] 2023-02-13 15:54
> @alexandis Any update?

I have resolved the error. But unfortunately I don't remember what it was... Something specific to my project. I mean that debug helped me to find the actual reason.

**Comment by chaimite** [comment] 2023-11-05 21:33
Hi. I had this problem and was getting desperate. I suspected that the problem would come from a few packages, so I went to the node_modules of those specific packages and checked their package.json and their dependencies. The message told me which module it was missing so I installed the correct version of the package ng15 and everything was working. I hope this can save other a few hours of having no idea of what's happening.
