### ISSUE TITLE
404 ERRORs on NPM.

### ISSUE THREAD

**Issue by montella1507** [FortAwesome/angular-fontawesome#390] opened 2022-12-04 08:45 UTC
Hello,

i think there are broken files on NPM for some versions. 

https://registry.npmjs.org/@fortawesome/angular-fontawesome/-/0.11.1/angular-fontawesome-0.11.1.tgz

 WARN  GET https://registry.npmjs.org/@fortawesome/angular-fontawesome/-/0.11.1/angular-fontawesome-0.11.1.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@fortawesome/free-regular-svg-icons/-/6.2.0/free-regular-svg-icons-6.2.0.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@fortawesome/fontawesome-common-types/-/6.2.0/fontawesome-common-types-6.2.0.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@fortawesome/fontawesome-svg-core/-/6.2.0/fontawesome-svg-core-6.2.0.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@fortawesome/free-brands-svg-icons/-/6.2.0/free-brands-svg-icons-6.2.0.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@fortawesome/free-solid-svg-icons/-/6.2.0/free-solid-svg-icons-6.2.0.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.

**Comment by devoto13** [comment] 2022-12-04 19:24
I'm not familiar with pnpm, but looks like some misconfiguration on your side. See e.g. https://github.com/pnpm/pnpm/issues/5561.

Package can be downloaded without issues using the URL resolved by npm - https://registry.npmjs.org/@fortawesome/angular-fontawesome/-/angular-fontawesome-0.11.1.tgz, so I don't think it is corrupted.

**Comment by devoto13** [comment] 2023-01-01 20:22
Hope you were able to resolve your problem by now.
If you still experience the problem and believe that there is a bug in `angular-fontawesome`, please provide a minimal reproduction we can look at.

**Closed by devoto13** 2023-01-01 20:22 UTC

**Comment by montella1507** [comment] 2023-01-02 08:50
Hello, sorry you were right i forgot to close this issue. Had to remove pnpm.lock and reinstall..

Thanks.
