### ISSUE TITLE
Feature request: Fontawesome custom kit module for icon library

### ISSUE THREAD

**Issue by Unidraga** [FortAwesome/angular-fontawesome#290] opened 2021-02-01 04:02 UTC
### Describe the problem you'd like to see solved or task you'd like to see made easier

I'm trying to set up my fontawesome custom kit with custom icons to become a module where I can import like the following

import { fas } from '@fortawesome/free-solid-svg-icons';
import { far } from '@fortawesome/free-regular-svg-icons';
**import { fak } from '@fortawesome/my-custom-fontawesome-kit';**

export class AppModule {
  constructor(library: FaIconLibrary) {
    library.addIconPacks(fas, far, **fak**);
  }
}

### Is this in relation to an existing part of angular-fontawesome or something new?
I believe this is something new as the fontawesome kit is relatively new

### What is 1 thing that we can do when building this feature that will guarantee that it is awesome?
Making integration of custom fontawesome kit with angular seamless.

### Why would other angular-fontawesome users care about this?
As more users start creating their own kits, they'll want to have the same implementation of icon library. It solves the issue of tree shaking since there isn't any tree to shake when all the icons you ever want for the application you're building is all in one library package.

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?
10 Absolutely right now. Otherwise, why would loyal, paying customers use the fontawesome kit, there are other solutions for custom icon kits out there. 

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/angular-fontawesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by devoto13** [comment] 2021-02-01 08:56
The `angular-fontawesome` library and Kits are designed to cover two distinct use cases:

- `angular-fontawesome` + icons packages are specifically for Angular, where you have a package manager to install packages and you have a build toolchain to perform dead code elimination
- Kits are more for CMS/static website use cases, where there is no build tooling/package manager and users are usually less tech-savvy, so they just want to add a single URL and be done for the day

I'm not sure if it is feasible to implement what you suggest. Basically, FA will have to publish a package for each Kit of every user and release a new version every time you modify the Kit and then you will have to update to the new version in your Angular app.

Is there any particular reason why you want to have such a Kit package instead of adding only the icons you use to the `FaLibrary` directly? Is it because you need a Kit for other projects and you don't want to add icons in two places? Or any other problem you experience?

**Comment by Unidraga** [comment] 2021-02-03 01:22
Is there any particular reason why you want to have such a Kit package instead of adding only the icons you use to the FaLibrary directly? 

There are 2 reasons for this:
1. As you mentioned I want a kit for multiple projects and I want to maintain it in one place.
2. There are in-house custom made icons that's not available on fontawesome (far, fas, fal, fab)

The project is using the angular stack which is why we are using angular-fontawesome package for our icons. It works well with the fontawesome packages(far,fas,fal,fab) and because it's well-wrapped, angular's property binding operator [] comes along with it and it's able to update the icon properly . 
e.g., 
_<fa-icon [icon]="getSelectedChartTypeIcon()"></fa-icon>_
where getSelectedChartTypeIcon() returns the selected icon name (prefix is set to fak)

I understand what you're saying about feasibility. However, if I'm unable to use the official angular-fontawesome wrapper with the custom kit, I'll have to find other means of loading custom icons and it'll probably be the angular material custom icon kit. 

However, the team likes the direction that fontawesome is going that's why we made a decision to invest in fontawesome. I understand that right now the kit will generate a script for usage with the <i> tag. I'm not sure what the details are but I'm under the impression that if it's able to generate a script for usage, it should be able to generate an npm package so that we can import it into the modules and use the icon library that comes with angular-fontawesome package.

If generating an npm package from the fontawesome kit is not the company's direction and that it is strictly for static/CMS websites, I'll need to report back and re-evaluate whether we should be using fontawesome kits.

If generating an npm package or some other ways of bridging the gap to use angular-fontawesome package for custom fontawesome kit is the way to go, I'd like to know a rough estimate on when that will be available.

**Comment by devoto13** [comment] 2021-02-03 14:31
Thanks for providing more details!

Re (2), it is possible to add custom icons to the `FaIconLibrary`. It is a bit cumbersome right now and not really documented (see #172 for more details), but I successfully use custom icons in my work project. Just to give you an example, this is [how](https://github.com/FortAwesome/angular-fontawesome/blob/master/src/testing/helpers.ts#L38) one would declare a custom icon, then it can be used the same way as an icon definition from the FA icon packages.

> If generating an npm package from the fontawesome kit is not the company's direction and that it is strictly for static/CMS websites

I'm only maintaining the `angular-fontawesome` library and not working for FA, so that was just my understanding of how things are. @robmadole, can you review this feature request and give the official response on providing NPM packages for Kits?

**Comment by thepercival** [comment] 2021-02-21 18:00
With angular strict-rules this would generate errors, but can be turned off.  I will read into the kit-solution

**Comment by Unidraga** [comment] 2021-02-24 18:21
Thanks @devoto13. 
While I'm still waiting on @robmadole for the official response on providing NPM packages for Kits.

I've gone ahead and started using the workaround that @devoto13 provided. However, I've encountered some issues and I've narrowed it down to potentially happen when the icons are loaded into the iconLibrary using the workaround method.

I've created custom icons and exported the SVGs with compound path. I've also checked the SVG paths on illustrator and on fontawesome Kit. I'll give examples of the same icon in different phases below.

SVG exported from illustrator (open up SVG file in notepad++):
\<svg id="Layer_1" data-name="Layer 1"
	xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
	\<defs>
		<style>.cls-1{fill:#0092b5;}</style>
	\</defs>
	\<path class="cls-1" d="M7.23,25.5l7-9.06L10.09,7.53h2.18l1.89,4.07c.66,1.4,1.13,2.51,1.44,3.32a35.94,35.94,0,0,1,2.32-3.22l3.23-4.17H23.7l-7.11,9.28,4,8.69H18.48l-2.4-5.25c-.22-.49-.49-1.15-.8-2A22.24,22.24,0,0,1,14,20.16L9.84,25.5ZM8.47,5h16.3m0-.52H8.47v1h16.3Z"/>
\</svg>

SVG that's uploaded to Kit (taken from inspecting the element):
\<svg aria-hidden="true" focusable="false" data-prefix="fak" data-icon="average" role="img"
	xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="flex-grow-1 svg-inline--fa fa-average fa-3x" style="width: 1em;">
	\<path fill="currentColor" d="M57.48 490.257l160.188-206.711L122.88 80.384h49.664l43.145 92.843q22.391 47.786 32.733 75.673a856.747 856.747 0 0153.01-73.42l73.693-95.096h58.027l-162.27 211.627 92.16 198.144h-49.015l-54.614-119.74q-7.475-16.486-18.295-45.227a496.674 496.674 0 01-30.072 43.213l-94.003 121.856zM85.778 23.211H457.83m0-11.947H85.777v23.893H457.83z" class="">\</path>
\</svg>

SVG that's imported into angular-fontawesome package with the following:
_export const faWeightedAverage: IconDefinition = {
  prefix: 'fac' as IconPrefix,
  iconName: 'weighted-average' as IconName,
  icon: [
    32,
    32,
    [],
    'f031',
    [
      'M7.23,25.5l7-9.06L10.09,7.53h2.18l1.89,4.07c.66,1.4,1.13,2.51,1.44,3.32a35.94,35.94,0,0,1,2.32-3.22l3.23-4.17H23.7l-7.11,9.28,4,8.69H18.48l-2.4-5.25c-.22-.49-.49-1.15-.8-2A22.24,22.24,0,0,1,14,20.16L9.84,25.5ZM8.47,5h16.3m0-.52H8.47v1h16.3Z',
    ],
  ],
};_

Note that the path given is the exact same path as the one that's exported from the illustrator.

After it's been imported into faIconLibrary, I used it using 
_<fa-icon [icon]="['fac', 'faWeightedAverage']></fa-icon>_

That's when things start to change.
SVG from inspector element on the project:
\<svg role="img" aria-hidden="true" focusable="false" data-prefix="fac" data-icon="weighted-average" class="svg-inline--fa fa-weighted-average fa-w-16 fa-fw"
	xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
	\<g class="fa-group">
		\<path class="fa-secondary" fill="currentColor" d="M7.23,25.5l7-9.06L10.09,7.53h2.18l1.89,4.07c.66,1.4,1.13,2.51,1.44,3.32a35.94,35.94,0,0,1,2.32-3.22l3.23-4.17H23.7l-7.11,9.28,4,8.69H18.48l-2.4-5.25c-.22-.49-.49-1.15-.8-2A22.24,22.24,0,0,1,14,20.16L9.84,25.5ZM8.47,5h16.3m0-.52H8.47v1h16.3Z">\</path>
		\<path class="fa-primary" fill="currentColor" d="undefined">\</path>
	\</g>
\</svg>

I'd like to shift your attention to the <g> tag which is grouping 2 paths. 
The 1st path having exactly what I input, and a 2nd path that's undefined (this was the culprit for the following error)
_Error: \<path> attribute d: Expected moveto path command ('M' or 'm'), "undefined"._

In addition to that, it's appending 2 classes. _fa-primary_ & _fa-secondary_ and that causes and issue of mismatch color tone with in-built fontawesome icons

![fontawesome color tone](https://user-images.githubusercontent.com/16644853/109045449-982f9700-76a1-11eb-959f-e61aa100c63e.JPG)
where the 1st(left) icon is in-built icons from fontawesome and 2nd(middle) and 3rd(right) icons are custom icons loaded using the method proposed [here](https://stackblitz.com/edit/angular-z8v4ux-i7gazy?file=src%2Fapp%2Fapp.module.ts)

At the end of the day, what I'm looking for is a way to have the SVG loaded without the additional grouping (\<g> tag), class (fa-secondary) and undefined path (\<path d="undefined">\</path>).
And of course, the official response.

**Comment by devoto13** [comment] 2021-02-24 18:31
@Unidraga I think the problem is that you should have a path without wrapping it into an array. I guess what happens is that renderer thinks, that you provide a duotone icon (which would have 2 paths inside an array: primary and secondary) and that's what causes the issue.

Sorry for confusion, the example I shared above used the duotone icon. Here is the one with your example icon, which seems to work as intended: https://stackblitz.com/edit/angular-z8v4ux-6hvw7b

**Comment by robmadole** [comment] 2021-02-24 19:53
@Unidraga you've also been chatting with us in support, correct? Can you reply to the thread we've started there please? As @devoto13 said he's a volunteer on this project and since you are a Pro customer we'll use that channel instead of this one. I'll  cross-post the outcome to this issue once we are finished but we need to isolate to one channel.

**Comment by Unidraga** [comment] 2021-02-24 22:52
@robmadole Oh! So that's what he meant when he said he's only maintaining the library and not working for FA. Will do! 

I've got an email thread started in support with Trevor so I'll use that channel instead. Thanks for your patience and guidance @devoto13 , you've been awesome and I appreciate it greatly.

**Comment by robmadole** [comment] 2021-03-02 16:48
We've been able to resolve the issue that @Unidraga had with using custom icons.

Regarding using Kits with the angular-fontawesome project: here are our (Font Awesome) thoughts on this.

The Kits product and the angular-fontawesome project are orthogonal to each other. We believe that if you are using Angular that angular-fontawesome is the best choice. The work that @devoto13 and the rest of the community have put in to this makes it the best choice and it's our first recommendation when any of our free or pro customers ask us.

The only wrinkle with this is that Kits provides a convenient way to upload custom icons that would then be valuable to use within an Angular project (via angular-fontawesome). So what we are committed to is making some of the features of Kits usable with our JavaScript frontend frameworks.

What this _might_ mean is that you have an npm-installable package that uses our private NPM registry that includes the custom icons you've uploaded into your Kit. So using your custom icons is familiar and is supported without any additional work from the framework packages (like angular-fontawesome).

Something like this:

```
import { fak } from '@fortawesome/fontawesome-kit-ae89becc01'
```

Nothing is set in stone other than the fact that we know we have some features from Kits that would be valuable to all of our JS component package frameworks. We certainly want to open this capability up because we think it's pretty friggin' cool :)

**Comment by devoto13** [comment] 2021-07-23 12:52
I'm going to close this issue as the original problem was resolved and I think it is better to follow official Font Awesome communication channels (like https://blog.fontawesome.com) for updates on the private npm packages for kits.

**Closed by devoto13** 2021-07-23 12:52 UTC
