### ISSUE TITLE
Using fa icon in standalone component

### ISSUE THREAD

**Issue by tgt87** [FortAwesome/angular-fontawesome#398] opened 2023-02-20 12:19 UTC
### Describe the problem
Hi, I'm trying to build an app using only standalone components as such I'm not having a app.module.ts file.
Instead I tried importing FontAwesomeModule into main.ts instead.
<img width="447" alt="image" src="https://user-images.githubusercontent.com/24860044/220100945-5d983e83-da19-4569-84f3-9221a19955ec.png">

I am also import the icon that I want to use in the component itself
<img width="366" alt="image" src="https://user-images.githubusercontent.com/24860044/220101339-f863f384-8cc8-4ea8-8763-f55ce73808f8.png">

However I'm getting the following error
![image](https://user-images.githubusercontent.com/24860044/220103309-2dee3242-2d40-4947-90ef-f57f434d9683.png)

Angular version: 14.2.0
"@fortawesome/angular-fontawesome": "^0.11.1",
"@fortawesome/fontawesome-svg-core": "^6.3.0",
"@fortawesome/free-regular-svg-icons": "^6.3.0",
"@fortawesome/free-solid-svg-icons": "^6.3.0",

Appreciate any advice on how I should do the import and use the icon correctly in a standalone component.

**Comment by devoto13** [comment] 2023-02-26 08:35
You would need to add `FontAwesomeModule` to the `BlockSummaryComponent`'s imports to make the components available to it.

**Comment by tgt87** [comment] 2023-02-26 13:49
Thanks @devoto13. Is there a way to add it globally so that I don't need to add the import to every component that is using it?

**Comment by devoto13** [comment] 2023-02-26 15:06
As far as I'm aware, there is no way to declare global components in Angular. A common pattern is to define a SharedModule which re-exports all commonly used components and modules. This way one only needs to import this shared module instead of all its contents separately.

**Comment by DaSchTour** [comment] 2023-02-26 18:09
> Thanks @devoto13. Is there a way to add it globally so that I don't need to add the import to every component that is using it? 

That's completely against the idea of standalone components. If you don't want to import it into every component you should not use standalone but create a module where you declare your components and then import the dependencies for all the declared components.

**Comment by devoto13** [comment] 2023-04-16 10:36
Hope you were able to resolve your problem by now.
I'm closing the issue as everything seems to work as intended.

**Closed by devoto13** 2023-04-16 10:36 UTC

**Comment by dstran** [comment] 2023-05-12 15:42
For those wondering, this is how I import the `FontAwesomeModule` to the component.

`
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faAtom } from '@fortawesome/free-solid-svg-icons';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss'],
    _**imports: [FontAwesomeModule],**_
    standalone: true
})
`
