### ISSUE TITLE
export 'ɵɵdefineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by ubugnu** [FortAwesome/angular-fontawesome#147] opened 2019-06-10 21:21 UTC
### Describe the problem

Getting error `WARNING in ./node_modules/@fortawesome/angular-fontawesome/fesm5/angular-fontawesome.js 162:55-73
"export 'ɵɵdefineInjectable' was not found in '@angular/core'` after angular compilled

### What did you expect?

I didn't expect to find these two theta `ɵɵ` characters in code

### Reproducible test case

```
npm install --save-dev @fortawesome/fontawesome-pro
npm install --save-dev @fortawesome/pro-solid-svg-icons
npm install --save-dev @fortawesome/pro-regular-svg-icons
npm install --save-dev @fortawesome/pro-light-svg-icons
npm install --save-dev @fortawesome/fontawesome-svg-core
npm install --save-dev @fortawesome/angular-fontawesome
```
### How to get rid of the error
Just remove the `ɵɵ` from `ɵɵdefineInjectable` in the 2 occurences in `./node_modules/@fortawesome/angular-fontawesome/fesm5/angular-fontawesome.js`

**Comment by devoto13** [comment] 2019-06-11 07:40
Looks like duplicate of https://github.com/FortAwesome/angular-fontawesome/issues/145. Please use 0.3.0 if you're using Angular 6 or 7 and 0.4.0 if you're using Angular 8.

**Comment by devoto13** [comment] 2019-06-27 13:09
Closing as duplicated of https://github.com/FortAwesome/angular-fontawesome/issues/145.
Please comment if you don't think that this is the case.

**Comment by devoto13** [comment] 2019-06-27 14:23
I've also updated the title, so this issue is easier to find as many users seem to have this problem.

**Comment by RajabMohammadi** [comment] 2019-07-10 06:47
@devoto13 Thanks worded for me change the version of fontawesome-angular from 0.4.4 to 0.3.0

**Comment by nilahdad** [comment] 2019-09-20 03:56
**WARNING in** ./node_modules/@ng-select/ng-select/fesm2015/ng-select-ng-select.js 2560:52-70
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

Just removed the **ɵɵ** from **ɵɵdefineInjectable** in the 3 occurrences in
./node_modules/@ng-select/ng-select/fesm2015/ng-select-ng-select.js

**and it's working properly, thanks.**

**Comment by MaryCooperGD** [comment] 2019-12-02 15:59
> **WARNING in** ./node_modules/@ng-select/ng-select/fesm2015/ng-select-ng-select.js 2560:52-70
> "export 'ɵɵdefineInjectable' was not found in '@angular/core'
> 
> Just removed the **ɵɵ** from **ɵɵdefineInjectable** in the 3 occurrences in
> ./node_modules/@ng-select/ng-select/fesm2015/ng-select-ng-select.js
> 
> **and it's working properly, thanks.**

Hi, thanks you saved me with this. Can you tell me why this happens and how one can prevent it?

**Comment by sonic1981** [comment] 2019-12-02 17:04
> **WARNING in** ./node_modules/@ng-select/ng-select/fesm2015/ng-select-ng-select.js 2560:52-70
> "export 'ɵɵdefineInjectable' was not found in '@angular/core'
> 
> Just removed the **ɵɵ** from **ɵɵdefineInjectable** in the 3 occurrences in
> ./node_modules/@ng-select/ng-select/fesm2015/ng-select-ng-select.js
> 
> **and it's working properly, thanks.**

That's a really bad solution

**Comment by MaryCooperGD** [comment] 2019-12-02 17:06
> > **WARNING in** ./node_modules/@ng-select/ng-select/fesm2015/ng-select-ng-select.js 2560:52-70
> > "export 'ɵɵdefineInjectable' was not found in '@angular/core'
> > Just removed the **ɵɵ** from **ɵɵdefineInjectable** in the 3 occurrences in
> > ./node_modules/@ng-select/ng-select/fesm2015/ng-select-ng-select.js
> > **and it's working properly, thanks.**
> 
> That's a really bad solution

Yes, it is :/ And that's why I was asking the reason behind that, to prevent that from happening ...

**Comment by robmadole** [comment] 2019-12-02 17:07
@MaryCooperGD @sonic1981 can you provide an alternate solution?

**Comment by MaryCooperGD** [comment] 2019-12-02 17:12
> @MaryCooperGD @sonic1981 can you provide an alternate solution?

No, in fact I was asking. If I had One, I would have already posted It. I'm Just trying to understand if Someone knows which reason Is behind this problem in node_modules. I'm doing other researches so if I Will find something I Will surely post it here.

**Comment by devoto13** [comment] 2019-12-02 17:14
The right solution for `@fortawesome/angular-fontawesome` package is to use correct version of the library depending on your version of Angular as pointed out [here](https://github.com/FortAwesome/angular-fontawesome/issues/147#issuecomment-500725328) and in the [README](https://github.com/FortAwesome/angular-fontawesome#compatiblity-table).

The right solution for `@ng-select/ng-select` (which is not in any way related to `@fortawesome/angular-fontawesome` and this issue tracker) is probably to use correct version as well judging from their [README](https://github.com/ng-select/ng-select#versions).

**Comment by devoto13** [comment] 2019-12-02 17:22
And the reason for this issue is that Angular 6 or 7 (don't remember exactly) used `ɵɵdefineInjectable` for the tree-shakable providers in the generated code for libraries (which got published to NPM). Then Angular 8 renamed this property to `defineInjectable` and broke all the libraries using tree-shakable providers. Then libraries got adapted and published new versions where generated code was using `defineInjectable`. And then Angular decided that it was not fun enough and replaced `defineInjectable` with `ɵɵdefineInjectable` and broken all the libraries using tree-shakable providers once again.

Because of this back and forth renaming you have to use specific versions of libraries with specific versions of Angular to ensure that the symbol, which is expected by the library is actually present in the the Angular bundles. Hope this explains the root cause of the problem.

**Closed by devoto13** 2019-12-02 17:22 UTC

**Comment by Morazajuan** [comment] 2020-05-13 07:47
@devoto13 you are my hero tonight! yes I am using Angular 6 and for certain reasons I can update it to the latest I was trying to install 

 npm i ngx-cookie-service

after you mentioned the versions, I tried an older one like

npm i ngx-cookie-service@2.0.1

and it did the trick! :) thank you so much spent like 3 hrs on it lol

**Comment by Sejal21** [comment] 2020-10-16 17:28
> and it did the trick! :) thank you so much spent like 3 hrs on it lol

Hey! I tried this but then it says ngx-cookie-service is not found :( 
Also I have not been able to use any of the ngx modules . 
I am using angular 6 and even if I update my core/cli , my material stops working.
