### ISSUE TITLE
Different version of fontawesome-common-types when installing package v.0.9.0

### ISSUE THREAD

**Issue by NickeManarin** [FortAwesome/angular-fontawesome#357] opened 2022-03-29 17:26 UTC
### Describe the problem

In September-October 2021 I created a (Angular v12.2.0) project and added FontAwesome using `ng add @fortawesome/angular-fontawesome@0.9.0`, then it added these references to my project:

```
    "@fortawesome/angular-fontawesome": "^0.9.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/pro-light-svg-icons": "^5.15.3",
    "@fortawesome/pro-regular-svg-icons": "^5.15.3",
    "@fortawesome/pro-solid-svg-icons": "^5.15.3",
```

These packages only reference `fontawesome-common-types@0.2.36`.

Today I'm creating another project using the same packages and noticed that I was getting an error when trying to pass an `IconDefinition` to an object:

Icon class:
```
import { IconDefinition } from '@fortawesome/fontawesome-common-types';

export class MenuItem {
  icon?: IconDefinition;
}
```

Class usage:
```
import { faUsers } from '@fortawesome/pro-regular-svg-icons';

this.items = [{ icon: faHomeAlt }] //Error.
```

The error message is this one:

> Type 'import("%@fortawesome/pro-regular-svg-icons/node_modules/@fortawesome/fontawesome-common-types/index").IconDefinition' is not assignable to 
type 'import("%@fortawesome/fontawesome-common-types/index").IconDefinition'.

That didn't make sense until I noticed that there's two references to `fontawesome-common-types`, for 0.3.0 and for 0.2.36:

![image](https://user-images.githubusercontent.com/14798947/160667219-de10ebe6-9123-4d3f-9acd-89d50aafcee0.png)

[package-lock.json.txt](https://github.com/FortAwesome/angular-fontawesome/files/8373662/FontAwesome.json.txt)

I tried updating these packages to the latest under 0.9.0, but to no avail:

```
    "@fortawesome/angular-fontawesome": "^0.9.0", //Same
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/pro-light-svg-icons": "^5.15.4",
    "@fortawesome/pro-regular-svg-icons": "^5.15.4",
    "@fortawesome/pro-solid-svg-icons": "^5.15.4",
```

Manually adding version 0.2.36 of the `fontawesome-common-types` did the trick.

```
"@fortawesome/fontawesome-common-types": "^0.2.36",
```

But it would be better if it was not necessary.

### What did you expect?

Installing version 0.9.0 should use the same internal packages.

### Reproducible test case

Is it needed? If so, ping me.

**Comment by devoto13** [comment] 2022-03-29 18:24
Hmm, this is pretty strange as `@fortawesome/fontawesome-svg-core@1.3.0` and `@fortawesome/fontawesome-common-types@0.3.0` should marked as deprecated exactly because of these breaking changes. So they should not be installed anymore.

And they are marked deprecated on the public NPM registry. But looks like packages in the Pro registry are not marked as deprecated. Any ideas why is it so @robmadole? Is it not supported by the Cloudsmith?

<details>
  <summary>This is what public NPM registry shows.</summary>

```
$ npm show @fortawesome/fontawesome-svg-core@1.3.0

@fortawesome/fontawesome-svg-core@1.3.0 | MIT | deps: 1 | versions: 67
The iconic font, CSS, and SVG framework
https://fontawesome.com

DEPRECATED ⚠️  - Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/

keywords: font, awesome, fontawesome, icon, svg, bootstrap

dist
.tarball: https://registry.npmjs.org/@fortawesome/fontawesome-svg-core/-/fontawesome-svg-core-1.3.0.tgz
.shasum: 343fac91fa87daa630d26420bfedfba560f85885
.integrity: sha512-UIL6crBWhjTNQcONt96ExjUnKt1D68foe3xjEensLDclqQ6YagwCRYVQdrp/hW0ALRp/5Fv/VKw+MqTUWYYvPg==
.unpackedSize: 374.4 kB

dependencies:
@fortawesome/fontawesome-common-types: ^0.3.0

maintainers:
- devoto13 <devoto13@gmail.com>
- jrjohnson <jon.johnson@ucsf.edu>
- robmadole <robmadole@gmail.com>
- supercodepoet <travis@travischase.me>
- fortawesome-admin <admin@fortawesome.com>
- mwilkerson <mwilkerson@gmail.com>

dist-tags:
latest: 6.1.1         next: 1.3.0-beta3     prerelease: 1.2.26-2

published a month ago by robmadole <robmadole@gmail.com>
```
</details>


<details>
  <summary>And this is what Pro registry shows.</summary>

```
$ npm show @fortawesome/fontawesome-svg-core@1.3.0

@fortawesome/fontawesome-svg-core@1.3.0 | MIT | deps: 1 | versions: 69
The iconic font, CSS, and SVG framework
https://fontawesome.com

keywords: font, awesome, fontawesome, icon, svg, bootstrap

dist
.tarball: https://npm.fontawesome.com/@fortawesome/fontawesome-svg-core/-/1.3.0/fontawesome-svg-core-1.3.0.tgz
.shasum: 343fac91fa87daa630d26420bfedfba560f85885
.integrity: sha512-UIL6crBWhjTNQcONt96ExjUnKt1D68foe3xjEensLDclqQ6YagwCRYVQdrp/hW0ALRp/5Fv/VKw+MqTUWYYvPg==

dependencies:
@fortawesome/fontawesome-common-types: ^0.3.0

dist-tags:
latest: 6.1.1      next: 1.3.0-beta3

published a month ago
```
</details>

@NickeManarin I would suggest to do the below in the meantime to avoid the deprecated 1.3.0 release and 0.3.0 types being installed:

```
$ npm i --save @fortawesome/fontawesome-svg-core@~1.2.36
```

**Comment by robmadole** [comment] 2022-04-02 18:29
@devoto13 I just missed the Pro repository. I've got this fixed now:

```
npm show --registry https://npm.fontawesome.com @fortawesome/fontawesome-svg-core@1.3.0
```

```
@fortawesome/fontawesome-svg-core@1.3.0 | MIT | deps: 1 | versions: 69
The iconic font, CSS, and SVG framework
https://fontawesome.com

DEPRECATED ⚠️  - Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/

keywords: font, awesome, fontawesome, icon, svg, bootstrap

dist
.tarball: https://npm.fontawesome.com/@fortawesome/fontawesome-svg-core/-/1.3.0/fontawesome-svg-core-1.3.0.tgz
.shasum: 343fac91fa87daa630d26420bfedfba560f85885
.integrity: sha512-UIL6crBWhjTNQcONt96ExjUnKt1D68foe3xjEensLDclqQ6YagwCRYVQdrp/hW0ALRp/5Fv/VKw+MqTUWYYvPg==

dependencies:
@fortawesome/fontawesome-common-types: ^0.3.0

dist-tags:
latest: 6.1.1      next: 1.3.0-beta3

published a month ago
```

**Comment by devoto13** [comment] 2022-04-03 09:34
Thanks, @robmadole!

I still seem to be getting an undeprecated response from the registry thought... Any ideas? I have tried with both the maintainer token and the Pro subscription access token.

```
$ npm show --registry https://npm.fontawesome.com @fortawesome/fontawesome-svg-core@1.3.0

@fortawesome/fontawesome-svg-core@1.3.0 | MIT | deps: 1 | versions: 69
The iconic font, CSS, and SVG framework
https://fontawesome.com

keywords: font, awesome, fontawesome, icon, svg, bootstrap

dist
.tarball: https://npm.fontawesome.com/@fortawesome/fontawesome-svg-core/-/1.3.0/fontawesome-svg-core-1.3.0.tgz
.shasum: 343fac91fa87daa630d26420bfedfba560f85885
.integrity: sha512-UIL6crBWhjTNQcONt96ExjUnKt1D68foe3xjEensLDclqQ6YagwCRYVQdrp/hW0ALRp/5Fv/VKw+MqTUWYYvPg==

dependencies:
@fortawesome/fontawesome-common-types: ^0.3.0

dist-tags:
latest: 6.1.1      next: 1.3.0-beta3

published a month ago
```

**Comment by robmadole** [comment] 2022-04-12 22:12
@devoto13 yeah this seems to be a problem with Cloudsmith. Let me ping them. I can reproduce it by connecting to a VPN in Germany.

**Comment by robmadole** [comment] 2022-04-13 21:57
@devoto13 Cloudsmith is working on this. I'll report back when I hear.

**Comment by devoto13** [comment] 2022-05-23 06:42
This seems to be fixed now and packages are marked as deprecated in the Pro registry. Please let us know if you still experience the issue and we'll look more into it.

**Closed by devoto13** 2022-05-23 06:42 UTC
