### ISSUE TITLE
(not a bug) Attribution when using the free SVG icons in a commercial Angular Project

### ISSUE THREAD

**Issue by dali-trabelsi** [FortAwesome/angular-fontawesome#387] opened 2022-11-20 23:17 UTC
I didn't know where I can ask this question so I thought I could add it here. 
Its all in the question, I am using Font Awesome **free SVG Icons** in a **commercial angular app** and I we are wondering if or where we should be attributing Font Awesome in our website

Quoting from the Font Awesome free license page at [https://fontawesome.com/license/free](https://fontawesome.com/license/free): 
> Downloaded Font Awesome Free files already contain embedded comments with sufficient attribution, so you shouldn't need to do anything additional when using these files normally.

We wanted to make sure whether we're safe using the SVG icons without having to do anything else.
Thanks in advance.

**Comment by devoto13** [comment] 2022-11-21 20:49
I'm an independent maintainer of this open-source project, so can't really provide you with legal advice. I would suggest contacting the company behind the FontAwesome using <a href="mailto:hello@fontawesome.com?subject=Hello, Font Awesome!" class="display-block no-underline">Contact Us</a> from the https://fontawesome.com.

Below is my understanding of things (not legal advice).

By default, Angular build strips all comments from the code and produces `dist/3rdpartylicenses.txt`, which among others includes `LICENSE.txt` from the icon packages. As this is not a comment in the code file, I am not sure if it fulfills the requirement from the quote, hence the recommendation to contact the company.

One can use `--extract-license false` when building an application, in this case, Angular CLI won't produce `dist/3rdpartylicenses.txt`, but also won't strip license comments from the files. You can see them appear in the `dist/main.xxx.js` files. The problem is that [`index.mjs`](https://cdn.jsdelivr.net/npm/@fortawesome/free-solid-svg-icons@6.2.1/index.mjs) used by `angular-fontawesome` does not have this license comment as [`index.js`](https://cdn.jsdelivr.net/npm/@fortawesome/free-solid-svg-icons@6.2.1/index.js) does for example. Which could actually be a bug, but I guess it does make it any easier to fulfill that attribution requirement 😄 To make it even more complex, none of the single-icon files have the license comment, and probably including it in each icon file could add a huge overhead to the package and bundle sizes.

I'm going to close this issue as it's not really a bug of the `angular-fontawesome` as you mentioned and refer you to the aforementioned Contact Us email. Feel free to post the result of that communication here as it may help other users wondering about the same topic.

**Closed by devoto13** 2022-11-21 20:49 UTC
