### ISSUE TITLE
crash browser border-radius

### ISSUE THREAD

**Issue by erdalceylan** [FortAwesome/angular-fontawesome#184] opened 2019-09-19 07:33 UTC
We have a problem. android 6.0 and google chrome browser(some versions)
image disappears when "border-radius" is used when multiple icons are used.

_many of our users encountered this problem_

userAgent : Mozilla/5.0 (Linux; Android 6.0.1; SM-J700F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.73 Mobile Safari/537.36

testUrl : https://stackblitz.com/edit/angular-z8v4ux-dl83mu

![sc1](https://user-images.githubusercontent.com/4347677/65222903-b6ff2680-dac8-11e9-8233-a6242d9b55ec.png)

----
----
![sc2](https://user-images.githubusercontent.com/4347677/65222911-bb2b4400-dac8-11e9-81fd-4868e66f6f6d.png)

**Comment by devoto13** [comment] 2019-09-19 08:08
@erdalceylan I tried to run your reproduction on Chrome 76.0.3809.132 and 77.0.3865.92 on Android 9 and Android 7 (the only devices I have at hand) and was not able to reproduce the problem. Image loads a bit longer than icons and is displayed after 2-3 seconds.

1. Have you tried to connect to the Chrome with Dev Tools and see if image is loaded, but just not rendered? Or is not loaded at all?
2. Was it happening on older versions of Google Chrome (75, 76?)? You run latest Chrome and this may be a rendering glitch introduced in the version 77.

**Comment by erdalceylan** [comment] 2019-09-19 10:49
@devoto13  yes loading and displaying images.
but the image disappears when "border-radius" is given to the image

devices with which we have problems
android 6.0.1 chrome 76.0 (samsung galaxy note 4)
android 6.0.1 chrome 77.0 (Samsung Galaxy J7)

**Comment by devoto13** [comment] 2019-09-19 11:07
Sorry, but I don't have any devices with Android 6.0.1 and given that issue does not reproduce on other devices using same versions of Chrome it sounds more like issue with the specific Android version, then with FontAwesome library. I would suggest to debug it further on your side.

**Comment by devoto13** [comment] 2019-11-27 20:46
I'm sorry, but without the way to reproduce the issue we can't do much to debug and fix it. Also it seems to be very specific to certain devices/versions.

I'm going to close this issue for now, but happy to re-open if new information allows to move this forward.

**Closed by devoto13** 2019-11-27 20:46 UTC
