### ISSUE TITLE
Package does not support schematics

### ISSUE THREAD

**Issue by jdflaugergues** [FortAwesome/angular-fontawesome#205] opened 2019-11-17 07:22 UTC
Hi !
I tried to install your angular-fontawesome component with `ng add @fortawesome/angular-fontawesome` command but it seems not to be recognized by the schematics API. 
I tried the latest version (0.5.0 and 0.6.0-alpha.0) but I always got the following error : 

```The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.```

Here is my env :

```
Angular CLI: 8.3.12
Node: 11.15.0
OS: linux x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.12
@angular-devkit/build-angular     0.803.12
@angular-devkit/build-optimizer   0.803.12
@angular-devkit/build-webpack     0.803.12
@angular-devkit/core              8.3.12
@angular-devkit/schematics        8.3.12
@angular/cli                      8.3.12
@ngtools/webpack                  8.3.12
@schematics/angular               8.3.12
@schematics/update                0.803.12
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by devoto13** [comment] 2019-11-17 10:26
@jdflaugergues Can you share the exact steps/command you've used? Schematics are only supported in `0.6.0-alpha-0` (which is a pre-release, so you need to explicitly specify the version). Running `ng add @fortawesome/angular-fontawesome@0.6.0-alpha.0` works for me as intended.

**Comment by jdflaugergues** [comment] 2019-11-17 14:21
It was exactly the same command as you I run before `ng add @fortawesome/angular-fontawesome@0.6.0-alpha.0`.
But with npm commands, it's work : 
```
npm install @fortawesome/fontawesome-svg-core
npm install @fortawesome/free-solid-svg-icons
npm install @fortawesome/angular-fontawesome@0.6.0-alpha.0
```

However, I've removed this three modules with npm uninstall and retried to install your component with ng command, and it's finally work.

**Comment by devoto13** [comment] 2019-11-17 14:40
I see. It fails because you had older version of `@fortawesome/angular-fontawesome` installed and there is a bug in Angular CLI, which was [recently fixed](https://github.com/angular/angular-cli/commit/3f57956c3282361f8909ff8b0d51471d708162eb). The problem is that `ng add` didn't check that you had a correct version installed and tried to run schematics from the older version of `@fortawesome/angular-fontawesome` which expectedly failed as there are no schematics in the older versions.

As your problem is resolved and the bug has already been fixed in the latest Angular CLI I'm going to close this issue.

The workaround as you correctly figured out is to `npm uninstall @fortawesome/angular-fontawesome` package and then run `ng add @fortawesome/angular-fontawesome@0.6.0-alpha.0`.

**Closed by devoto13** 2019-11-17 14:40 UTC

**Comment by jdflaugergues** [comment] 2019-11-17 18:56
Yes, you can close this issue. The workaround works.
Thanks.
