### ISSUE TITLE
fa-layers-counter not working in prod

### ISSUE THREAD

**Issue by AmbroiseVuaridel** [FortAwesome/angular-fontawesome#160] opened 2019-08-08 21:00 UTC
### Describe the problem

i got everything working perfectly with ionic 4 and angular 7 with fortawesome 0.3.0,
it is truly awesome.

Unfortunately i have an issue when building for prod : ionic build --prod -- --base-href ./
the badges seem not to be working in this case (it works with ionic serve or ionic build without prod), the code in question is :
      <fa-layers class="fa-fw" slot="end">
        <fa-icon [icon]="['fas','shopping-cart']"></fa-icon>
        <fa-layers-counter [content]="46" class="fa-icon-counter"></fa-layers-counter>
      </fa-layers>

this code comes from this tuto to get angular fontawesome work on ionic : https://ionicacademy.com/font-awesome-ionic-4/
(may need to login for free)

### What did you expect?

I expected the badge to be visible, exactly as in dev

**Comment by devoto13** [comment] 2019-08-08 22:00
Do you get any errors/warnings in the console? May be related to https://github.com/FortAwesome/angular-fontawesome/issues/154.

I personally don't use Ionic, so it's hard to say what may be the issue. If you setup a minimal repro and put it on GitHub, so it is possible to clone, run and observe the problem I can try to debug it.

**Comment by devoto13** [comment] 2019-08-08 22:01
Also you do have your code wrapped into `fa-layers` component, right?

```
<fa-layers>
  <fa-icon [icon]="['fas','shopping-cart']">
  <fa-layers-counter [content]="46" class="fa-icon-counter">
</fa-layers>
```

**Comment by devoto13** [comment] 2019-08-08 22:03
Also [`content` is a `string`](https://github.com/FortAwesome/angular-fontawesome/blob/master/src/lib/layers/layers-text-base.component.ts#L35), so it should be either  `<fa-layers-counter [content]="'46'">` or `<fa-layers-counter content="46">`.

**Comment by AmbroiseVuaridel** [comment] 2019-08-09 09:00
Hello @devoto13, Thank you for your comments!
I just realized the problem is only on firefox, not chrome.
There is no errors/warnings in the console.
I did not enable Ivy.
it is indeed wrapped into a fa-layers component like this:
      <fa-layers class="fa-fw" slot="end">
        <fa-icon [icon]="['fas','shopping-cart']"></fa-icon>
        <fa-layers-counter [content]="'46'" class="fa-icon-counter"></fa-layers-counter>
      </fa-layers>
I tried to put a string instead of numbers, it changed nothing.

**Comment by devoto13** [comment] 2019-08-09 09:03
@AmbroiseVuaridel Then, please, prepare a minimal reproduction of the problem as requested in https://github.com/FortAwesome/angular-fontawesome/issues/160#issuecomment-519703238. Without the reproduction it is hard to assist your further.

**Comment by AmbroiseVuaridel** [comment] 2019-08-09 15:58
@devoto13  
I have really narrowed down the problem to firefox (latest version), just run the below repro below, you'll see a 46 badge on the cart icon on chrome but not firefox
https://github.com/AmbroiseVuaridel/fortawesome_minimal_repro

**Comment by devoto13** [comment] 2019-08-10 00:02
The reason is that you use non-standard `zoom` property, which is not supported by Firefox: https://caniuse.com/#feat=css-zoom, position of the counter element gets messed up and that's why you don't see it. If you remove all custom styling the counter will become visible, but very small (which is tracked in https://github.com/FortAwesome/angular-fontawesome/issues/165).

I would recommend to use dev tools of the browser to debug such issues: select desired element in the element tree and observe where it is located, then try disabling CSS properties until issue is found.

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/823594/62814710-b612c680-bb12-11e9-8161-7ae759b5144a.png">

Closing as this is not bug in angular-fontawesome.

**Closed by devoto13** 2019-08-10 00:02 UTC
