### ISSUE TITLE
Stacking icons is not appearing correctly

### ISSUE THREAD

**Issue by plasmy** [FortAwesome/angular-fontawesome#329] opened 2021-10-05 15:49 UTC
I am using this code:

```
        <fa-stack>
            <fa-icon [icon]="['far', 'circle']" style="font-size: 8px;" stackItemSize="2x"></fa-icon>
            <fa-icon icon="file-alt" stackItemSize="1x"></fa-icon>
        </fa-stack>
```

And I am getting the following result: 

![image](https://user-images.githubusercontent.com/5615530/136057570-a776c965-19e1-4884-91a2-a9df7667ec30.png)

How can I get the document icon to center inside the circle? I have already tried text-align and forcing a margin, but none work.

**Comment by devoto13** [comment] 2021-10-05 19:53
@plasmy I can't reproduce it in the fresh project, the icon is properly centered in my case. Maybe some global styles in your project interfere with the fa-icon? Please provide a minimal reproduction demonstrating the problem. There is not much we can do to help you without it. You can start by creating a new project with:

```
$ ng new repro
$ cd repro
$ ng add @fortawesome/angular-fontawesome
```

Then add minimal code producing the misaligned icon, push it to the repository on GitHub and share a link here, so I can debug and fix it if it turns out to be a bug in the library.

**Comment by sorinfratila** [comment] 2022-02-25 08:27
Hi, here is reproducible repro on stackblitz. This is still an issue particularly for angular 9.

https://stackblitz.com/edit/angular-fontawesome-avmhcl?file=app%2Fapp.component.html

**Comment by devoto13** [comment] 2022-02-27 15:17
Thanks for the reproduction @sorinfratila! I can observe the issue there. I'll look into it as soon as I can.

**Comment by devoto13** [comment] 2022-02-27 15:39
@sorinfratila There is a problem in your StackBlitz. It loads `fontawesome.css` file (belonging to FA 5.0.7 according to the text) from the external source, which conflicts with `angular-fontawesome` styles and breaks the stacked icon. If StackBlitz was not so broken (😛), you could have removed the file then everything would work as expected. Are you able to reproduce the issue in the StackBlitz where that external file is not present?

**Comment by sorinfratila** [comment] 2022-03-07 09:54
@devoto13 that is indeed correct. I updated the [stackblitz](https://stackblitz.com/edit/angular-font-awesome-starter-f44maa?file=src%2Fapp%2Fapp.component.ts) and removed the css file and the stacked icon looks good now.

Thank you for pointing that out.

**Comment by devoto13** [comment] 2022-03-18 23:06
Closing as the problem was caused by a user error. Please open a new issue with minimal reproduction if you still experience the problem.

**Closed by devoto13** 2022-03-18 23:06 UTC
