### ISSUE TITLE
Styles apply in server side is delay few second

### ISSUE THREAD

**Issue by vdporiginals** [FortAwesome/angular-fontawesome#248] opened 2020-04-30 11:54 UTC
### Describe the problem

When i use angular universal and try set font-size for fa-icon but it apply delay few second after page loaded( the icon get bigger in few second then comeback to normal). it is still work ok in client side.
![Capture](https://user-images.githubusercontent.com/60820356/80706896-49fa4780-8b13-11ea-9fdf-937cb892dca1.PNG)

### What did you expect?

i want it style apply is right

**Comment by devoto13** [comment] 2020-04-30 12:09
@vdporiginals This sounds like a duplicate of https://github.com/FortAwesome/angular-fontawesome/issues/48. Please use the workaround from https://github.com/FortAwesome/angular-fontawesome/issues/48#issuecomment-432543956 for now.

**Closed** 2020-04-30 12:18 UTC
