### ISSUE TITLE
has no exported member

### ISSUE THREAD

**Issue by dolanmiu** [FortAwesome/angular-fontawesome#25] opened 2018-03-29 02:04 UTC
When I follow the instructions, I get this error:

![image](https://user-images.githubusercontent.com/2917613/38066024-ef46cfee-32fd-11e8-8ede-04de207bd172.png)

**Comment by MichaelGambold** [comment] 2018-03-29 03:43
I had the same issue after just installing this. After running a `npm update` I no longer got the error messages and was able to get past this. The versions of the packages after the update are listed below.

@fortawesome/fontawesome-svg-core   1.2.0-10      1.2.0-10      1.2.0-7
@fortawesome/free-solid-svg-icons        5.1.0-7        5.1.0-7        5.1.0-4

**Comment by mlwilkerson** [comment] 2018-03-29 04:30
We did have some problems with a pre-release in the past 24 hours or so, to which those errors have some relevance, though I'm not sure if it's the same issue. The problems we identified were fixed in  #24 in the follow-up pre-release `@fortawesome/angular-fontawesome@0.1.0-8`.

@dolanmiu can you tell me which version of `@fortawesome/angular-fontawesome` is involved in those errors?

And then, yes, definitely makes sure that you've updated to `0.1.0-8`

As for the supporting packages, the best pre-release versions to use with the `@fortawesome/angular-fontawesome@0.1.0-8` pre-release are currently the most recent:

`@fortawesome/fontawesome-svg-core@1.2.0-10`
`@fortawesome/free-solid-svg-icons@5.1.0-7`

(Use the same `5.1.0-7` for any other icon content package as well, like `free-solid-svg-icons`.)

So @dolanmiu if you do those updates and still see those errors, I'm going to be curious with more questions.

**Comment by wartab** [comment] 2018-03-29 08:51
@fortawesome/fontawesome-svg-core does not seem to be installed with @fortawesome/angular-fontawesome, as it is only a dev-dependency. Is it mandatory to add it ourselves (wasn't a few days ago).

**Comment by wartab** [comment] 2018-03-29 08:57
After installing the latest version on NPM of even @fortawesome/fontawesome-svg-core I get this:

```
ERROR in node_modules/@fortawesome/angular-fontawesome/layers/layers-counter.component.d.ts(1,10): error TS2305: Module '"C:/Users/Vincent Lycoops/projects/web-accounting/node_modules/@fortawesome/fontawesome-svg-core/index"' has no exported member 'Counter'.
node_modules/@fortawesome/angular-fontawesome/layers/layers-counter.component.d.ts(1,19): error TS2305: Module '"C:/Users/Vincent Lycoops/projects/web-accounting/node_modules/@fortawesome/fontawesome-svg-core/index"' has no exported member 'CounterParams'.
node_modules/@fortawesome/angular-fontawesome/layers/layers-text-base.component.d.ts(2,37): error TS2305: Module '"C:/Users/Vincent Lycoops/projects/web-accounting/node_modules/@fortawesome/fontawesome-svg-core/index"' has no exported member 'TextParams'.
node_modules/@fortawesome/angular-fontawesome/layers/layers-text.component.d.ts(1,16): error TS2305: Module '"C:/Users/Vincent Lycoops/projects/web-accounting/node_modules/@fortawesome/fontawesome-svg-core/index"' has no exported member 'TextParams'.
```

**Comment by dolanmiu** [comment] 2018-03-29 10:09
I will check tonight, at work at the moment

**Comment by devoto13** [comment] 2018-03-29 11:51
My educated guess it that the root cause is that some of the pre-releases don't have `latest` tag on the NPM on the latest pre-release :) As a result people get 2 versions of core in their node_modules and run into all sort of troubles. If you install packages by using concrete versions than everything should work. Following installation instructions from README will lead to the above error.

**Comment by mlwilkerson** [comment] 2018-03-29 12:26
@wartab We did move `fontawesome-svg-core` to a `peerDependencies` in a recent pre-release, and updated the installation instructions in [README.md](https://github.com/FortAwesome/angular-fontawesome/blob/master/README.md) accordingly. So yes, this would require installing it separately.

@devoto13 Yes, the `latest` dist-tag. That's almost certainly what it is. I thought I'd got all of those updated when I released. But I just saw that the `latest` of `fontawesome-svg-core` was not yet updated. That's almost certainly the problem. I've just marked `fontawesome-svg-core@1.2.0-10` with `latest`.

Try again now?

**Comment by wartab** [comment] 2018-03-29 15:06
Thank you, that fixes everything. In PHPStorm, I use autocompletion to keep NPM packages up to date, so @latest is usually what I go for for most packages.

**Comment by mlwilkerson** [comment] 2018-03-29 16:48
OK, thanks for the report.

**Closed by mlwilkerson** 2018-03-29 16:48 UTC

**Comment by dolanmiu** [comment] 2018-03-29 23:17
@mlwilkerson I was using `@fortawesome/angular-fontawesome@1.2.0-7`

Updated to `@fortawesome/angular-fontawesome@1.2.0-10`

Seemed to have fixed it :)

**Comment by mlwilkerson** [comment] 2018-03-29 23:28
Yeah, there have definitely been some volatile changes between those pre-release versions. We're close to locking down and stabilizing a real release soon, though. Thanks for the feedback, and sorry for the trouble.

If I'm not mistaken, though, the package@version strings you mentioned above are mismatched. I think I know what you mean, I just want to call that out so that others don't come along and copy-paste them.

You mean that you updated the core library `@fortawesome/fontawesome-svg-core` from `1.2.0-7` to `1.2.0-10`, right?

**Comment by dolanmiu** [comment] 2018-03-30 01:14
@mlwilkerson Yup, I upgraded `@fortawesome/fontawesome-svg-core` from 1.2.0-7 to 1.2.0-10.

When I first installed `@fortawesome/fontawesome-svg-core` last night for the very first time, it installed `1.2.0-7` by default for some reason. `1.2.0-7` seems to have been released a while ago. 

When doing it again, it seemed to have got `1.2.0-10`

**Comment by mlwilkerson** [comment] 2018-03-30 01:25
Right, that's because `1.2.0-7` was the one tagged `latest` when you initially installed. It was earlier today that I added the `latest` tag to the `1.2.0-10` prerelease. By default, if you don't include a version number with the package you install, it will try to install the `latest`. Normally a prerelease like this wouldn't be `latest`, but in the case of this Angular component, we've been regarding the whole thing as prerelease status until we reached a point of stability for a first "real" release. And we're just about there.

**Comment by deveshsinghal22** [comment] 2018-04-04 09:29
"@fortawesome/fontawesome-svg-core": "^1.2.0-10",

I am still getting this error. 
 `ERROR in node_modules/@fortawesome/angular-fontawesome/icon/icon.component.d.ts(2,22): error TS2307: Cannot find module '@fortawesome/fontawesome-svg-core'.
node_modules/@fortawesome/angular-fontawesome/layers/layers-counter.component.d.ts(1,40): error TS2307: Cannot find module '@fortawesome/fontawesome-svg-core'.
node_modules/@fortawesome/angular-fontawesome/layers/layers-text-base.component.d.ts(2,55): error TS2307: Cannot find module '@fortawesome/fontawesome-svg-core'.
node_modules/@fortawesome/angular-fontawesome/layers/layers-text.component.d.ts(1,34): error TS2307: Cannot find module '@fortawesome/fontawesome-svg-core'.
node_modules/@fortawesome/angular-fontawesome/shared/models/props.model.d.ts(1,97): error TS2307: Cannot find module '@fortawesome/fontawesome-svg-core'.
src/app/app.component.ts(5,24): error TS2307: Cannot find module '@fortawesome/free-solid-svg-icons'.
`

am i missing anything?

**Comment by wartab** [comment] 2018-04-04 11:58
As @mlwilkerson said, you need to add "@fortawesome/fontawesome-svg-core" as dependency yourself now, as it is only a peer dependency in this package.
