### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by launcelot66** [FortAwesome/angular-fontawesome#240] opened 2020-03-30 10:50 UTC
### Describe the problem

update cli/core/material to 9.1/9.2 version (global cli 9.1, node 13.9) and got errors while serve app:

`Error: Error when flattening the source-map ".../app/node_modules/@fortawesome/angular-fontawesome/config.d.ts.map" for ".../app/node_modules/@fortawesome/angular-fontawesome/config.d.ts": RangeError: Maximum call stack size exceeded

Error: Error when flattening the source-map ".../app/node_modules/@fortawesome/angular-fontawesome/icon-library.d.ts.map" for ".../app/node_modules/@fortawesome/angular-fontawesome/icon-library.d.ts": RangeError: Maximum call stack size exceeded

Error: Error when flattening the source-map ".../app/node_modules/@fortawesome/angular-fontawesome/stack/stack-item-size.directive.d.ts.map" for ".../app/node_modules/@fortawesome/angular-fontawesome/stack/stack-item-size.directive.d.ts": RangeError: Maximum call stack size exceeded

Error: Error when flattening the source-map ".../app/node_modules/@fortawesome/angular-fontawesome/icon/icon.component.d.ts.map" for ".../app/node_modules/@fortawesome/angular-fontawesome/icon/icon.component.d.ts": RangeError: Maximum call stack size exceeded

Error: Error when flattening the source-map ".../app/node_modules/@fortawesome/angular-fontawesome/icon/duotone-icon.component.d.ts.map" for ".../app/node_modules/@fortawesome/angular-fontawesome/icon/duotone-icon.component.d.ts": RangeError: Maximum call stack size exceeded

Error: Error when flattening the source-map ".../app/node_modules/@fortawesome/angular-fontawesome/layers/layers.component.d.ts.map" for ".../app/node_modules/@fortawesome/angular-fontawesome/layers/layers.component.d.ts": RangeError: Maximum call stack size exceeded

Error: Error when flattening the source-map ".../app/node_modules/@fortawesome/angular-fontawesome/layers/layers-counter.component.d.ts.map" for ".../app/node_modules/@fortawesome/angular-fontawesome/layers/layers-counter.component.d.ts": RangeError: Maximum call stack size exceeded

Error: Error when flattening the source-map ".../app/node_modules/@fortawesome/angular-fontawesome/layers/layers-text.component.d.ts.map" for ".../app/node_modules/@fortawesome/angular-fontawesome/layers/layers-text.component.d.ts": RangeError: Maximum call stack size exceeded

Error: Error when flattening the source-map ".../app/node_modules/@fortawesome/angular-fontawesome/stack/stack.component.d.ts.map" for ".../app/node_modules/@fortawesome/angular-fontawesome/stack/stack.component.d.ts": RangeError: Maximum call stack size exceeded

Error: Error when flattening the source-map ".../app/node_modules/@fortawesome/angular-fontawesome/fontawesome.module.d.ts.map" for ".../app/node_modules/@fortawesome/angular-fontawesome/fontawesome.module.d.ts": RangeError: Maximum call stack size exceeded

Error: Error when flattening the source-map ".../app/node_modules/@fortawesome/angular-fontawesome/angular-fontawesome.d.ts.map" for ".../app/node_modules/@fortawesome/angular-fontawesome/angular-fontawesome.d.ts": RangeError: Maximum call stack size exceeded`

### What did you expect?

serve without errors

### Reproducible test case

just update from v9 to v 9.1 and serve project (TSLint v 6.1)

**Comment by devoto13** [comment] 2020-03-30 11:22
I'm sorry, but while this is probably a valid error it will take a lot of time for me to re-create your setup and reproduce this error. Please create a new CLI project, add a minimal code to reproduce this problem and push it on GitHub, so I'm able to clone it, run `ng serve` and observe the error. This way I can debug and fix it if it is a bug in `@fortawesome/angular-fontawesome` package.

I'm not able to reproduce it with the fresh project, so it is likely to be an issue in your setup/CLI/elsewhere:

```
$ ng new crash-fa
$ cd crash-fa
$ ng add @fortawesome/angular-fontawesome
$ ng serve
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/animations/browser/testing : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @fortawesome/angular-fontawesome : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @fortawesome/angular-fontawesome/testing : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 58.3 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 141 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 9.77 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 2.83 MB [initial] [rendered]
Date: 2020-03-30T11:21:52.862Z - Hash: b96266e63cc1c474fe2a - Time: 5944ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
```

**Comment by davidecampello** [comment] 2020-03-31 12:57
same error for me.

Before update I had:
`
    "@angular/animations": "~9.0.2",

    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/localize": "^9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
     ....
    "@angular-devkit/build-angular": "~0.900.3",
    "@angular/cli": "~9.0.3",
    "@angular/compiler-cli": "~9.0.2",
    "@angular/language-service": "~9.0.2",
`

and now I have:
`
    "@angular/animations": "~9.1.0",

    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/localize": "^9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
`

**Comment by launcelot66** [comment] 2020-03-31 13:04
y package.json after update:

> "dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/material": "^9.2.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@fortawesome/angular-fontawesome": "^0.6.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.27",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "~9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@types/node": "^13.9.2",
    "@types/jasmine": "~3.5.9",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }

**Comment by devoto13** [comment] 2020-03-31 13:11
@davidecampello @launcelot66 Unfortunately versions won't help to move this forward. The example I posted above uses same versions. I've tried to add the `@angular/material` to my repository and still `ng serve` completed successfully. On top of the above:

```
$ ng add @angular/material
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? Choose a prebuilt theme name, or "custom" for a custom theme: Indigo/Pink        [ Preview: https://material.angular.io?theme=indigo-pink ]
? Set up global Angular Material typography styles? No
? Set up browser animations for Angular Material? Yes
UPDATE package.json (1502 bytes)
✔ Packages installed successfully.
UPDATE src/app/app.module.ts (516 bytes)
UPDATE angular.json (3787 bytes)
UPDATE src/index.html (487 bytes)
UPDATE src/styles.css (181 bytes)
$ ng serve
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/cdk/clipboard : es2015 as esm2015
Compiling @angular/cdk/layout : es2015 as esm2015
Compiling @angular/cdk/text-field : es2015 as esm2015
Compiling @angular/cdk/accordion : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/cdk/table : es2015 as esm2015
Compiling @angular/cdk/stepper : es2015 as esm2015
Compiling @angular/cdk/tree : es2015 as esm2015
Compiling @angular/material/expansion : es2015 as esm2015
Compiling @angular/material/core : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015
Compiling @angular/cdk/drag-drop : es2015 as esm2015
Compiling @angular/material/divider : es2015 as esm2015
Compiling @angular/material/button : es2015 as esm2015
Compiling @angular/material/tooltip : es2015 as esm2015
Compiling @angular/material/form-field : es2015 as esm2015
Compiling @angular/material/icon : es2015 as esm2015
Compiling @angular/material/dialog : es2015 as esm2015
Compiling @angular/material/sort : es2015 as esm2015
Compiling @angular/material/card : es2015 as esm2015
Compiling @angular/material/badge : es2015 as esm2015
Compiling @angular/material/button-toggle : es2015 as esm2015
Compiling @angular/material/bottom-sheet : es2015 as esm2015
Compiling @angular/material/input : es2015 as esm2015
Compiling @angular/material/select : es2015 as esm2015
Compiling @angular/material/autocomplete : es2015 as esm2015
Compiling @angular/material/checkbox : es2015 as esm2015
Compiling @angular/material/grid-list : es2015 as esm2015
Compiling @angular/material/chips : es2015 as esm2015
Compiling @angular/material/icon/testing : es2015 as esm2015
Compiling @angular/material/paginator : es2015 as esm2015
Compiling @angular/material/datepicker : es2015 as esm2015
Compiling @angular/material/list : es2015 as esm2015
Compiling @angular/material/progress-spinner : es2015 as esm2015
Compiling @angular/material/progress-bar : es2015 as esm2015
Compiling @angular/material/radio : es2015 as esm2015
Compiling @angular/material/menu : es2015 as esm2015
Compiling @angular/material/sidenav : es2015 as esm2015
Compiling @angular/material/slide-toggle : es2015 as esm2015
Compiling @angular/material/slider : es2015 as esm2015
Compiling @angular/material/stepper : es2015 as esm2015
Compiling @angular/material/snack-bar : es2015 as esm2015
Compiling @angular/material/table : es2015 as esm2015
Compiling @angular/material/tabs : es2015 as esm2015
Compiling @angular/material/toolbar : es2015 as esm2015
Compiling @angular/material/tree : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 58.8 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 141 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 179 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.17 MB [initial] [rendered]
Date: 2020-03-31T13:09:33.473Z - Hash: fc3c889272e5aabdc0ee - Time: 8287ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
```

Until you produce and share a minimal reproduction repository, where I can observe the problem there is not much I can do to fix it.

**Comment by devoto13** [comment] 2020-03-31 13:20
Can you check https://github.com/angular/angular/issues/35757 for some potential solutions? It doesn't seem to be an error in `angular-fontawesome`.

**Comment by davidecampello** [comment] 2020-03-31 13:43
Thanks for the answer. I'll try

**Comment by davidecampello** [comment] 2020-03-31 13:54
Manually removing the node_modules folder and installing again has worked for me. I have no errors now.
Thanks

**Comment by devoto13** [comment] 2020-04-03 14:01
I'm going to close this issue as there is nothing to fix on the `@fortawesome/angular-fontawesome` side. If you still experience it and have a reproduction, open new issue on the Angular issue tracker, so they can fix it. Otherwise refer to https://github.com/angular/angular/issues/35757 for a set of workarounds.

**Closed by devoto13** 2020-04-03 14:01 UTC
