### ISSUE TITLE
Argument of type 'import("/frontend/node_modules/@fortawesome/free-solid-svg-icons/node_modules/@fortawesome/fontawesome-common-types/index").IconPack' is not assignable to parameter of type  'import("/frontend/node_modules/@fortawesome/fontawesome-common-types/index").IconPack'.  23     iconLibrary.addIconPacks(fas);

### ISSUE THREAD

**Issue by sahilchahal** [FortAwesome/angular-fontawesome#350] opened 2022-03-11 10:28 UTC
### Argument of type 'import("/frontend/node_modules/@fortawesome/free-solid-svg-icons/node_modules/@fortawesome/fontawesome-common-types/index").IconPack' is not assignable to parameter of type  'import("/frontend/node_modules/@fortawesome/fontawesome-common-types/index").IconPack'.  23     iconLibrary.addIconPacks(fas);

Getting this error when using this library. Tried deleting package-lock.json and node modules but it didn't work.

## package.json
<img width="685" alt="Screenshot 2022-03-11 at 3 57 42 PM" src="https://user-images.githubusercontent.com/86303421/157849796-e11dce11-5554-4e40-acc9-472f47441b53.png">

**Comment by devoto13** [comment] 2022-03-11 11:53
Duplicate of https://github.com/FortAwesome/angular-fontawesome/issues/125#issuecomment-1053580697. See that comment for a solution.

**Closed by devoto13** 2022-03-11 11:53 UTC
