### ISSUE TITLE
Doesn't work inside ViewEncapsulation.ShadowDom

### ISSUE THREAD

**Issue by chan-dev** [FortAwesome/angular-fontawesome#322] opened 2021-08-04 04:22 UTC
### Describe the problem
Fontawesome icons doesn't work inside ShadowDom

### What did you expect?
I expect it to work but i guess since fontawesome styles are added globally and ShadowDom prevents non-inherited styles from leaking in, some css styles won't be applied.
Any workarounds for now?

**Comment by devoto13** [comment] 2021-08-04 11:23
I'm not using ShadowDom, so not sure exactly. Maybe one can manually add a `<link href="/assets/styles.css" rel="stylesheet">` inside the component using ShadowDom? You can find the stylesheet in the `@fortawesome/fontawesome-svg-core` package and should be able to copy it using `assets` in the `angular.json` file.

Closing as duplicate of #96

See also #18 and #48 for more information on the problem.

**Closed by devoto13** 2021-08-04 11:23 UTC

**Comment by chan-dev** [comment] 2021-08-05 01:22
@devoto13 Thanks, the workaround indeed worked.
What i did was import it under the sass file of the component with `ViewEncapsulation.DOM`.

/* app.component.scss */

:host {
  all: initial;
}

`@import "~@fortawesome/fontawesome-svg-core/styles";`
