### ISSUE TITLE
Error in angular 'was not found' FontAwesomeModule

### ISSUE THREAD

**Issue by charry0821** [FortAwesome/angular-fontawesome#61] opened 2018-06-22 19:58 UTC
Hi
I have the next problem:

"export 'FontAwesomeModule' was not found in '@fortawesome/angular-fontawesome'

This problem appear when i import the module in the app.mudule.ts and this error dont allows run the application, when i go to import in the module does not show alerts or error in the app.module.ts but when i go run ng serve spear the before error and dont show nothing in the browser.

Thanks for your answers

**Comment by mlwilkerson** [comment] 2018-06-22 20:24
This is probably a duplicate of #57 . If so, we have a fix already in `master` via #59. Once we get the docs wrapped up in #60 we'll release a new npm package version.

TL:DR; downgrade to the pre-release of this component `0.1.0-10` for now.

**Closed by mlwilkerson** 2018-06-22 20:24 UTC

**Comment by charry0821** [comment] 2018-06-22 20:46
Yes, that is the solution. Thanks @mlwilkerson
